version: "3"

services:
  nginx:
    image: datasetu/video-server
    container_name: nginx
    hostname: nginx
    restart: on-failure
    ports:
      - "1935:1935"
      - "3002:3002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/local/nginx/html/index.html
      - .:/root/datasetu-video-server/

  auth:
    image: datasetu/vs-auth-backend
    container_name: auth
    hostname: auth
    restart: on-failure
    volumes:
      - ./auth-backend:/root/auth-backend
      - .:/root/datasetu-video-server/
