version: "3"

services:
  nginx-rtmp:
    image: datasetu/video-server
    container_name: nginx
    hostname: nginx
    restart: on-failure
    ports:
      - "1935:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/root/datasetu-video-server/

  auth-backend:
    image: datasetu/vs-auth-backend
    container_name: auth
    hostname: auth
    restart: on-failure
    volumes:
      - /root/datasetu-video-server/auth-backend:/root/auth-backend
