name: test-suite

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'true'

    - name: Add host
      run: sudo echo "127.0.0.1  video.datasetu.org" | sudo tee -a /etc/hosts

    - name: Install python and required packages
      run: sudo apt-get update && sudo apt-get -y install ca-certificates openssl libssl-dev python3-setuptools python3-pip ffmpeg

    - name: Install python libraries required for tests
      run: sudo cat /etc/ffserver.conf && sudo pip3 install -r images/video-server/requirements.txt

    - name: Install video-server
      run: cd setup && ./install

    - name: Checking logs
      run: cd setup && ./logs nginx

    - name: Run tests
      run:  cd test && python3 test_init.py