name: test-suite

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'true'

    - name: Install python and required packages
      run: sudo apt-get -y install python3-setuptools build-essential libpq-dev python-dev python-pip python3-dev python3-pip python3-venv python3-wheel ffmpeg

    - name: Install python libraries required for tests
      run: sudo python3 -m pip install -r images/video-server/requirements.txt

    - name: Install video-server
      run: cd setup && ./install

    - name: Run tests
      run:  cd test && python3 test_init.py